### ISSUE TITLE
Generate Further Pre-Training Corpus

### ISSUE THREAD

**Issue by chenhz12** [xuyige/BERT4doc-Classification#23]
Hi,
Thank you for sharing your code. I met the following problem when running "python generate_corpus_agnews.py".

Traceback (most recent call last):
  File "generate_corpus_agnews.py", line 18, in <module>
    f.write(str(test_data[i][1])+"\n")
IndexError: index 1 is out of bounds for axis 0 with size 1

And also, could provide some guideline on how I can apply your code on my own dataset?

**Comment by zl-liu** [comment]
I have the same problem

**Comment by xuyige** [comment]
thank you for your issue, 
i think this may be because the format of your dataset is different to that we used
