### ISSUE TITLE
max_sequence_length in create_pretraining_data

### ISSUE THREAD

**Issue by LNdoremi** [xuyige/BERT4doc-Classification#8]
你好，非常感谢，这个项目对我目前的工作很有帮助。我在做学生作文自动评分的项目，数据量是450mb，大约93万篇学生作文。我用create_pretraining_data这个脚本生成了一个17G的tf.records 文件，max_sequence_length 选择的是128。我的问题是：在生成预训练数据这个步骤中，max_sequence_length 是选择最大的文章的长度，还是最长的一句话的长度？

**Comment by xuyige** [comment]
非常抱歉现在才回复
选择最大的文章长度比较好，或者是最长的一句话的长度乘2
但是请不要超过512

**Comment by LNdoremi** [comment]
好的，非常感谢您抽空回复。
